-- ==========================================
-- SCRIPT TẠO DATABASE CHO ĐÁM CƯỚI CÔNG GIÁO
-- ==========================================

-- 1. TẠO BẢNG RSVP (Xác nhận tham dự)
CREATE TABLE public.rsvp (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    guests integer NOT NULL DEFAULT 0,
    attending boolean NOT NULL DEFAULT true,
    message text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Bật Row Level Security (RLS) để bảo mật
ALTER TABLE public.rsvp ENABLE ROW LEVEL SECURITY;

-- Chính sách 1.1: Cho phép tất cả mọi người gửi form (INSERT)
CREATE POLICY "Khách mời có thể gửi RSVP" 
ON public.rsvp FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Chính sách 1.2: Cho phép xem danh sách (SELECT) cho Admin Dashboard
CREATE POLICY "Cho phép xem danh sách RSVP" 
ON public.rsvp FOR SELECT 
TO anon, authenticated 
USING (true);

-- Chính sách 1.3: Cho phép xóa (DELETE) cho Admin Dashboard
CREATE POLICY "Cho phép xóa RSVP" 
ON public.rsvp FOR DELETE 
TO anon, authenticated 
USING (true);


-- 2. TẠO BẢNG BANK_ACCOUNTS (Thông tin mừng cưới)
CREATE TABLE public.bank_accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role text NOT NULL CHECK (role IN ('bride', 'groom')),
    account_holder text NOT NULL,
    account_number text NOT NULL,
    bank_name text NOT NULL,
    qr_code_url text
);

-- Bật Row Level Security
ALTER TABLE public.bank_accounts ENABLE ROW LEVEL SECURITY;

-- Chính sách 2.1: Cho phép khách mời đọc thông tin STK (SELECT)
CREATE POLICY "Tất cả mọi người đều xem được STK" 
ON public.bank_accounts FOR SELECT 
TO anon, authenticated 
USING (true);

-- 3. THÊM DỮ LIỆU MẪU CHO BANK_ACCOUNTS
-- Thay mã số tài khoản và thông tin bằng thông tin thật của bạn
INSERT INTO public.bank_accounts (role, account_holder, account_number, bank_name, qr_code_url)
VALUES 
('bride', 'PHAM THI NHAN', '8840769381', 'BIDV', '/image/nganhangcodau.jpg'),
('groom', 'NGUYỄN VĂN THƯỜNG', '000000000', 'Không có', NULL);

-- Mẹo: Để tạo ảnh QR Code (qr_code_url), bạn có thể dùng vietqr.io hoặc up ảnh xịn của bạn vào Storage của Supabase rồi lấy Link chép vào chữ NULL bên trên (có dấu nháy đơn, ví dụ: 'https://link-anh/qr.jpg').
